# Rust files
rust:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.rs'
          - '**/Cargo.toml'
          - '**/Cargo.lock'

# Documentation
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**/*'

# GitHub Actions
github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/*'
          - '.github/actions/*'
